### ISSUE TITLE
Wiki: Is it possible to use the library to create csv output as well

### ISSUE THREAD

**Issue by varsraja** [vdjagilev/nmap-formatter#144]
I would like to know if we can use the library option to convert the xml file into csv.
And also would like to know if the library is as updated as the actual binary available for use.

**Comment by vdjagilev** [comment]
Hi @varsraja 
Library got updated and now you need to use v2, I've updated examples there and there is simple csv example here https://github.com/vdjagilev/nmap-formatter/wiki/Use-as-a-library#use-nmap-to-create-simplest-csv

The latest binary can be found on releases https://github.com/vdjagilev/nmap-formatter/releases page as well (in archive)
