### ISSUE TITLE
Long lines troubles

### ISSUE THREAD

**Issue by MiichaelKlimenko** [vdjagilev/nmap-formatter#148]
Too long lines in the file lead to the following error: bufio.Scanner: token too long
Unfortunately, I can't provide nmap XML scans for privacy reasons, but this problem occurs when converting large files (tested on a file of about 30MB).
This error is contained in the formatter/file.go file, because the buffer sizes for reading lines were not specified.
Suggestions for fixing this bug were offered in the merge request #147 

Additional resources:
https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

**Comment by vdjagilev** [comment]
Hey @MiichaelKlimenko !
Thanks for reporting the issue, I've took a bit different approach https://github.com/vdjagilev/nmap-formatter/pull/149 can you check that solution as well? XML unmarshaling is not very effective on large files, so I thought I could resolve multiple problems at the same time.

**Comment by MiichaelKlimenko** [comment]
Thanks for the reply! 
Yes, I confirm that your solution #149  works as well.
In addition, the conversion has become noticeably faster.

**Comment by vdjagilev** [comment]
Fixed in https://github.com/vdjagilev/nmap-formatter/pull/149 
https://github.com/vdjagilev/nmap-formatter/releases/tag/v2.1.5
