### ISSUE TITLE
JSON: output numbers as numbers instead of strings

### ISSUE THREAD

**Issue by ict-one-nl** [vdjagilev/nmap-formatter#60]
Great project to get the data into Elastic :) One thing is bothering ES, everything is a string in the json output, even stuff like port numbers. This makes it difficult to filter stuff. Could the numeric stuff be parsed that way?

Thanks!

**Comment by vdjagilev** [comment]
Fixed in version v0.3.0. Now some fields are integers, like start timestamp, end timestamp, ports, elapsed time, discovered services number, et cetera. Also added docker image https://github.com/vdjagilev/nmap-formatter/pkgs/container/nmap-formatter
